name: Linux oldconfig test

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the ukl-5.14 branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  LINUX_COMPLIE_TEST:
  
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
          
      #Checkout Linux repo - branch 5.14      
      - name: checkout Linux Repo
        uses: actions/checkout@v2
        with:
            path: linux
      
      # Installs required packages for build
      - name: Update and install package requirements
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get install git build-essential flex bison libelf-dev libssl-dev texinfo libgmp3-dev libmpc-dev libmpfr-dev qemu-kvm supermin 
          
        
       # Checks-out Makefile from repo
      - name: Checkout min-initrd directory
        uses: actions/checkout@v2
        with:
          repository: like101101/min-initrd
          path: min-initrd
          
      # Compile the kernel
      - name: Compile the kernel
        run: |
          make -C linux oldconfig
          make -C linux -j$(nproc)
          
      # Boot the Kernel
      - name: Boot the Kernel
        run: |  
          ls
          cd min-initrd 
          make build-package
          make all
          export SUPERMIN_KERNEL=/boot/vmlinuz-5.14.0 export SUPERMIN_MODULES=/lib/modules/5.14.0+/
          
      # Runs Boot Test
      - name: Boot Test Run
        run: |
          cd min-initrd
          qemu-system-x86_64 -smp cpus=1 -m 3g -no-reboot -kernel ../linux/arch/x86/boot/bzImage -initrd min-initrd.d/initrd -hda min-initrd.d/root -nodefaults -nographic -serial file:"../test.out" -append "console=ttyS0 root=/dev/sda net.ifnames=0 biosdevname=0 nowatchdog nosmap nosmep mds=off ip=192.168.19.136:::255.255.255.0::eth0:none -- -m /workloads/iperf.xml -a" -netdev tap,id=vlan1,ifname=tap0,script=no,downscript=no,vhost=on,queues=4 -device virtio-net-pci,mq=on,vectors=10,netdev=vlan1,mac=02:00:00:04:00:29
